<table class="table table-primary table-condensed table-borderless">
<thead>
    <tr>
        <th>Dag</th>
        <th>Vanaf</th>
        <th>Tot</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td>Maandag</td>
        <td>9:00</td>
        <td>21:00</td>
    </tr>
    <tr>
        <td>Dinsdag</td>
        <td>9:00</td>
        <td>17:00</td>
    </tr>
    <tr>
        <td>Woensdag</td>
        <td>9:00</td>
        <td>21:00</td>
    </tr>
    <tr>
        <td>Donderdag</td>
        <td>9:00</td>
        <td>17:00</td>
    </tr>
    <tr>
        <td>Vrijdag</td>
        <td>9:00</td>
        <td>14:00</td>
    </tr>
</tbody>
</table>